# fly.toml app configuration file generated for ivan-cv on 2023-06-13T12:01:17+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ivan-cv"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
