# fly.toml app configuration file generated for polished-water-5219 on 2023-10-15T13:16:22+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "polished-water-5219"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
